###############################################################################
# Copyright 2016, Julius Krah                                                 #
# by the @authors tag. See the LICENCE in the distribution for a              #
# full listing of individual contributors.                                    #
#                                                                             #
# Licensed under the Apache License, Version 2.0 (the "License");             #
# you may not use this file except in compliance with the License.            #
# You may obtain a copy of the License at                                     #
# http://www.apache.org/licenses/LICENSE-2.0                                  #
# Unless required by applicable law or agreed to in writing, software         #
# distributed under the License is distributed on an "AS IS" BASIS,           #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.    #
# See the License for the specific language governing permissions and         #
# limitations under the License.                                              #
###############################################################################


# When devtools is activated, override the default of 'spring.jpa.hibernate.ddl-auto'
# of embedded databases from 'create-drop' to 'create'. The hot reload server closes 
# the database before hibernate can drop the schema. Anyways, it's not really necessary
# to drop database since the datastore is in-memory
server:
  port: 8082

#  mail:
#    transport.protocol: smtp
#    host: smtp.gmail.com
#    port: 587
#    username: duc.bui.appdev@gmail.com
#    password: zaq!@WSXCDE
#    from.email: duc.bui.appdev@gmail.com
#    properties: 
#    mail.smtp.auth: true
#    mail.smtp.starttls.enable: true
#    mail.smtp.starttls.required: true

spring:
  datasource:
    hikari:
      allow-pool-suspension: true
      connection-timeout: 1000
    # set the database name. The connection string is auto-configured by spring-boot
    # ;DB_CLOSE_ON_EXIT=FALSE is part of the default config
    name: testDb
  jpa:
    database: h2
#    generate-ddl: false 
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2
#quartz:
#  enabled: true

# Every 5 seconds
#simplejob:
#  frequency: 5000            

liquibase:
  enabled: false    


schedule :
  jobs :
    -
      cronExpression : 0 0/5 * * * ?
      dataToWrite : First job
    -
      cronExpression : 0 0/7 * * * ?
      dataToWrite : Second job         
